<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Emo-Girl" failures="1" tests="8" name="Default test" time="25.384" errors="0" timestamp="2025-05-27T13:14:24 CDT">
  <testcase classname="tests.CheckoutTest" name="checkoutWithMissingInfoTest" time="1.125"/>
  <testcase classname="tests.CheckoutTest" name="checkoutWithValidInfoTest" time="1.61">
    <failure type="java.lang.AssertionError" message="expected [THANK YOU FOR YOUR ORDER] but found [Thank you for your order!]">
      <![CDATA[java.lang.AssertionError: expected [THANK YOU FOR YOUR ORDER] but found [Thank you for your order!]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:575)
at org.testng.Assert.assertEquals(Assert.java:585)
at tests.CheckoutTest.checkoutWithValidInfoTest(CheckoutTest.java:25)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- checkoutWithValidInfoTest -->
  <testcase classname="tests.CheckoutTest" name="checkoutWithoutFirstNameTest" time="1.487"/>
  <testcase classname="tests.CheckoutTest" name="checkoutWithoutLastNameTest" time="1.395"/>
  <testcase classname="tests.CheckoutTest" name="checkoutWithoutPostalCodeTest" time="1.453"/>
  <testcase classname="tests.CheckoutTest" name="verifyCheckoutPageTitleTest" time="0.906"/>
  <testcase classname="tests.CheckoutTest" name="verifyFinishPageURLTest" time="1.579"/>
  <testcase classname="tests.CheckoutTest" name="verifyOrderSummaryTest" time="1.229"/>
</testsuite> <!-- Default test -->
